---
- name: "Check my ID and permissions"
  hosts: controller
  tasks:
    - ansible.builtin.debug:
        msg: "My UID is: {{ lookup('pipe', 'id -u') | int }}"
      become: false
    - ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /vagrant/.vagrant/machines/main/libvirt/private_key
        - /home/vagrant/vagrant/.vagrant/machines/main/libvirt/private_key
      register: file_stat
    - ansible.builtin.debug:
        msg: |
          File: {{ item.item }} UID:{{ item.stat.uid }} GID: {{ item.stat.gid }} Mode: {{ item.stat.mode }} Esiste: {{ item.stat.exists | default(false) }}
      loop: "{{ file_stat.results }}"
- name: "Ping: check all hosts"
  tags: ping
  hosts: all
  tasks:
    - name: "ping"
      ansible.builtin.ping:
- name: "Vars: show variables"
  tags: vars
  hosts: all
  gather_facts: false
  tasks:
    - debug:
        var: vars
- name: "Multiarch i386 to target_hosts"
  tags: target
  hosts: target_hosts
  become: true
  tasks:
    - name: "Verify if i386 architecture is allready enabled"
      ansible.builtin.command: dpkg --print-foreign-architectures
      register: foreign_archs
      changed_when: false
      check_mode: false
    - name: "Add i386 architecture (if missing)"
      ansible.builtin.command: dpkg --add-architecture i386
      when: "'i386' not in foreign_archs.stdout_lines"
      become: true
    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['pkg_mgr'] == 'apt'
      become: true
- name: "Install syslinux multiarch for 32-bit boot support"
  tags: target
  hosts: target_hosts
  become: true
  tasks:
    - ansible.builtin.apt:
        name:
          - syslinux:i386          # contains the actual 32-bit boot binaries: syslinux.bin, isolinux.bin, ldlinux.c32...
          - syslinux-common        # shared files: menu.c32, vesamenu.c32, etc. (architecture-independent)
          - mtools                 # needed to write to FAT filesystems from Linux
          - parted
        state: present
        update_cache: true
      become: true
- name: "Restore insecure Vagrant SSH public key"
  tags: target
  hosts: target_hosts
  become: true
  tasks:
    - ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
        exclusive: true  # This deletes any other key and keeps ONLY this one
